services:
  db:
    container_name: db
    image: postgres:17-alpine3.21
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    env_file:
      - "./envs/postgres.env"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    ports:
      - "5432:5432"

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.0-p1
    volumes:
      - "./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt"
    ports:
      - "6432:6432"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost" ]

volumes:
  pg_data:
