services:
  db:
    container_name: db
    image: postgres:17-alpine3.21
    env_file:
      - "./envs/postgres.env"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.0-p1
    ports:
      - "6432:6432"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost" ]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 10s
    volumes:
      - "./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt"

  pgadmin4:
      container_name: pgadmin
      image: elestio/pgadmin:REL-9_4
      restart: always
      env_file:
        - "./envs/pgadmin.env"
      ports:
        - "8080:8080"
      depends_on:
        - db
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8080/", "||", "exit", "1"]
        interval: 40s
        timeout: 30s
        retries: 3
        start_period: 10s
      volumes:
        - "pgadmin_data:/pgadmin4/data"

volumes:
  pg_data:
  pgadmin_data:
